---
version: "3.7"


services:
  esphome:
    image: ghcr.io/imagegenius/esphome:latest
    container_name: esphome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ESPHOME_DASHBOARD_USE_PING=false #optional
    volumes:
      - ./esphome/config:/config
    ports:
      - 6052:6052
    restart: unless-stopped
  espcam-secserver:
    image: techblog/espcam-secserver
    container_name: espcam-secserver
    restart: always
    environment:
      - GREEN_API_INSTANCE_ID=
      - GREEN_API_TOKEN=
      - TARGET=
      - MESSAGE=Someone opened the door
    ports:
      - "8200:80"