---
version: "3.7"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "8091:9000"
    networks:
      - internal
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      # - SONARQUBE_JDBC_URL=
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=false"
      
  sonarqube-db:
    image: postgres
    container_name: sonarqube-db
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./sonarqube/postgresql:/var/lib/postgresql
      - ./sonarqube/postgresql_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.ouroboros.enable=true
      - traefik.enable=false

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest # 
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ./mealie/data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    restart: always


networks:
  internal:
    name: internal
    external: true


