---
version: "3.7"

services:

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    volumes:
      - ./deluge:/config
      - /mnt/downloads/:/mnt/downloads
      - /mnt/media/Kids/:/mnt/media/Kids
      - /mnt/media/Parents/:/mnt/media/Parents
      - ./joal/torrents:/mnt/torrents
      - ./deluge/auth/:/var/lib/deluge/.config/deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ip-nextgen/US Silicon Valley
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    networks:
      - docker


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads/:/mnt/downloads
      - /mnt/media/:/mnt/media
      - ./joal/torrents:/mnt/torrent
    ports:
      - 6882:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - docker

  telegram-download-daemon:
    image: alfem/telegram-download-daemon
    container_name: Telegram_Downloader
    restart: always
    environment:
      TELEGRAM_DAEMON_API_ID: ""
      TELEGRAM_DAEMON_API_HASH: ""
      TELEGRAM_DAEMON_CHANNEL: ""
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
      TELEGRAM_DAEMON_TEMP: "/tmp"
      TELEGRAM_DAEMON_DUPLICATES: "rename"
    volumes:
       - ./downloads:/downloads
       - ./tbdownloader/sessions:/session
       - /tmp:/tmp
    networks:
      - docker

  joal: 
    image: anthonyraymond/joal
    container_name: joal
    restart: always
    environment:
      - joal.ui.path.prefix=
      - joal.ui.secret-token=
      - spring.main.web-environment=true
      - server.port=15538
    volumes:
      - ./joal:/data
    ports:
      - 15538:15538
    command: ["--joal-conf=/data"]
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    networks:
      - docker

  sonarr:
  #This Container is for Sonarr https://sonarr.tv/
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    restart: always
    volumes:
      - ./sonarr:/config
      - /mnt/downloads/:/mnt/downloads
      - /mnt/media/Kids/:/mnt/media/Kids
      - /mnt/media/Parents/:/mnt/media/Parents
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8989:8989"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - docker

  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    restart: always
    volumes:
      - ./jackett:/config
      - /mnt/downloads/:/mnt/downloads
      - /mnt/media/Kids/:/mnt/media/Kids
      - /mnt/media/Parents/:/mnt/media/Parents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "9117:9117"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    networks:
      - docker

  radarr:
  #This Container is for Radarr https://radarr.video/
    image: "linuxserver/radarr"
    container_name: "radarr"
    restart: always
    volumes:
      - ./radarr:/config
      - /mnt/downloads/:/mnt/downloads
      - /mnt/media/Kids/:/mnt/media/Kids
      - /mnt/media/Parents/:/mnt/media/Parents
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7878:7878"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - docker

  lidarr:
  #This Container is for Lidarr https://lidarr.audio/
    container_name: lidarr
    image: volikon/lidarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
    - "8686:8686"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    volumes:
    - ./lidarr/config:/config
    - /mnt/downloads/:/mnt/downloads
    - /mnt/media/Kids/:/mnt/media/Kids
    - /mnt/media/Parents/:/mnt/media/Parents
    - /etc/localtime:/etc/localtime:ro
    networks:
      - docker

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr/config:/config
      - /mnt/downloads/:/mnt/downloads
      - /mnt/media/Kids/:/mnt/media/Kids
      - /mnt/media/Parents/:/mnt/media/Parents
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 6767:6767
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    networks:
      - docker


networks:
  docker:
    name: docker
    external: true
