---
version: "3.7"

services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: always
    volumes:
      - ./plex:/config
      - ./plex/transcode:/transcode
      - /mnt/media/Kids/:/media/kids
      - /mnt/media/Parents/:/media/parents
    network_mode: host
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=false"
    environment:
      - TZ=${TZ}
      - HOSTNAME=${PLEX_HOSTNAME}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - NVIDIA_VISIBLE_DEVICES=ALL
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # count: 1
            capabilities: [gpu]
  tautulli:
    container_name: tautulli
    restart: always
    image: linuxserver/tautulli
    volumes:
    - ./tautulli/config:/config
    - ./tautulli/logs:/logs:ro
    ports:
    - "8181:8181"
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    networks:
      - docker

  conreq:
    container_name: conreq
    restart: always
    image: ghcr.io/roxedus/conreq:latest
    ports:
      - "8884:8000"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./conreq/config:/config
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=false"
    networks:
      - docker

networks:
  docker:
    name: docker
    external: true